### ISSUE TITLE
Is this project completely abandoned or not ?

### ISSUE THREAD

**Issue by hardcod3dd** [lysep-corp/ButOSX#38]
Is there any plans to add more features or development news ? Any other resources or projects you can refer ?

**Comment by candestan** [comment]
I have plans to rewrite it from scratch. Just i don't know is CS 2 will support MACOS or not. I assume it's gonna support so i'm planning to rewrite it when CS 2 releases. If it's not, than i can consider updating it. But it's on my todo list. It is just abandoned for now.

**Comment by candestan** [comment]
First of all idk is hooks are ready inside the project i don't remember properly. You can implement very easly after implementing the hooks. Some features may need some offset and signature finiding that's the hard part for you. You need to reverse the game properly. On macos, you can use hopper dissassembler but it has a trial version of it. My suggestion is just dump the macos binaries and reverse it on a windows environment using ghidra or ida. That's it actually and i'm assuring you it is not easy as writing what to do.

**Comment by candestan** [comment]
Btw i'm shocked the fact of this project still works.

**Comment by hardcod3dd** [comment]
yep. all features still work, i just inject via lldb lol. i got a new m2 mac there is nothing to do so i thought what if i port cheats to mac for fun. it looks hard tho i dont know if i have the time for it. if you continue to develop this publicly leave a crypto donation address next time i would love to donate some for your efforts.

(eline saglik bu arada kac sene gecmis hala catir cutur calisiyor 😂)
